services:
  activemq:
    image: 'apache/activemq-classic:latest'
    ports:
      - '61616'
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432'
  pulsar:
    image: 'apachepulsar/pulsar:latest'
    ports:
      - '6650'
      - '8080'
    command: 'bin/pulsar standalone'
  zipkin:
    image: 'openzipkin/zipkin:latest'
    ports:
      - '9411'
